name: Deploy 2 K8s
on:
  push:
    branches:
      - main

jobs:
  build-n-deploy:
    runs-on: self-hosted
    steps:
        - name: checkout Code
          uses: actions/checout@v4 

        - name: Deploy 2 k8s
          run: |

            kubectl apply -f deployment.yaml
            kubectl get pods -l app=eshop-web
            kubectl get services